channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=21.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.2.1
  - numpy==1.26.3
  - packaging==23.2
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.0
  - scipy==1.12.0
name: mlflow-env
